# 10.2 Examples


#### This week:

* A couple of miscellaneous items: plotting lines with colormap color, integer word length and sets
* Lorenz equations 
* Recaman's sequence

In [1]:
%pylab ipympl

Populating the interactive namespace from numpy and matplotlib


### Set
A set is an unordered collection of items. Every element is unique (no duplicates) and must be immutable (which cannot be changed).

In [ ]:
set?

In [3]:
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}

In [4]:
A.union(B)

{1, 2, 3, 4, 5, 6, 7, 8}

In [5]:
A.intersection(B)

{4, 5}

In [7]:
if 4 in A.intersection(B): print("True")

True


In [8]:
aa = {}  # this is a dictionary

In [10]:
# empty set
aa = set()

In [12]:
aa.add(23)

In [13]:
aa

{23}

In [14]:
for i in range(3):
    aa.add(i)

In [15]:
aa

{0, 1, 2, 23}

In [21]:
if 3 in [3,5,4,3]: print("True")

True


In [19]:
ia = array(ones(5), dtype='int')

In [20]:
ia

array([1, 1, 1, 1, 1])

### Integer arrays and word length
The word length determines how many integers an integer variable (_memory slot_) can distinguish.

In [22]:
2**16

65536

In [37]:
n=257
ia = array(ones(n),dtype='int64')  # try with int8

In [31]:
ia

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [41]:
2**63/1e18

9.223372036854776

In [ ]:
# 2**7   # need one bit for sign

In [35]:
for i in range(n):
    ia[i] = i

In [36]:
ia

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99,  100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
        110,  111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
        121,  122,  123,  124,  125,  126,  127, -128, -127, -126, -125,
       -124, -123, -122, -121, -120, -119, -118, -117, -116, -115, -114,
       -113, -112, -111, -110, -109, -108, -107, -1

### Plotting colored lines on black background

In [42]:
import matplotlib.pyplot as plt

In [46]:
# ax.axis?

In [43]:
fig, ax = plt.subplots(facecolor='k')
#ax.axis('equal')
ax.axis('off')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(0.0, 1.0, 0.0, 1.0)

In [47]:
x = linspace(0,2*pi,100)
ax.plot(x,sin(x))


#### Plotting with a color from a color map

In [54]:
cm = plt.cm.get_cmap('autumn')

In [53]:
cm(0.9)

(1.0, 1.0, 0.6139702022054964, 1.0)

In [55]:
fig, ax = plt.subplots(facecolor='k')
#ax.axis('equal')
ax.axis('off')

cm = plt.cm.get_cmap('hot')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [58]:
0.5/xmax

0.07957747154594767

In [59]:
xmax = 2*pi
x = linspace(0,xmax,100)
color = cm(0.5/xmax)

ax.plot(x,sin(x),c=color)

#### Plotting each segment with a color map

In [63]:
for i in range(1000): close(i)

In [64]:
fig, ax = plt.subplots(facecolor='k')
#ax.axis('equal')
ax.axis('off')

cm = plt.cm.get_cmap('hsv')

n = 100; nd = 10
xmax = 2*pi
x = linspace(0,xmax,n*nd)

def plot_sin(x,c=(0,0,0,0)):
    ax.plot(x,sin(x),c=c)

for i in range(n): 
    color = cm(x[i*nd]/xmax)
    plot_sin(x[i*nd:i*nd+nd+1],c = color)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

#### Plot arc through $a_n$ and $a_{n-1}$ 
Imagine you have two points on a number ray that represent subsequent elements of a sequence. Draw a half circle through these two points.

In [65]:
an, an_ = 6,3 ; n = 3

In [67]:
fig, ax = plt.subplots(facecolor='k')
ax.axis('equal')
ax.axis('off')

center = (an + an_)/2.
radius = abs(an - an_)/2
x = linspace(-radius,radius,1000)
y = sqrt(radius**2 - x**2) * (-1)**n
ax.plot(x+center,y)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [69]:
fig, ax = plt.subplots(facecolor='k')
ax.axis('equal')
ax.axis('off')

def plot_arc(an, an_, n):
    center = (an + an_)/2.
    radius = abs(an - an_)/2
    x = linspace(-radius,radius,1000)
    y = np.sqrt(radius**2 - x**2) * (-1)**n
    ax.plot(x+center,y)

plot_arc(an, an_, n)
savefig('arc.png')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

**Demonstrate download and upload of figure**

## Lorenz equations
One of the most celebrated sets of differential equations in physics is the [Lorenz equations](https://en.wikipedia.org/wiki/Lorenz_system):
$$ \frac{dx}{dt} = \sigma(y-x) $$ $$\frac{dy}{dt} = rx -y -xz$$ $$\frac{dz}{dt} = xy - bz$$ where $\sigma$, $r$ and $b$ are constants. (The names of these constants may seem arbirtrary and odd but are always used in these equations -- _for historical reasons_).

Use the range from $t = 0$ to $t = 50 $ with the intial condition $(x,y,z) = (1,1,1)$, and solve with parameters $\sigma=10.0$, $r=28$ and $b=8/3$.

Use the scipy solver `integrate.solve_ivp`.

In [1]:
%pylab ipympl
from scipy import integrate

Populating the interactive namespace from numpy and matplotlib


In [3]:
def lorenz_rhs_ode(t,yy,params):
    '''
    Righ-hand-side (RHS) of Lorenz equations for scipy.integrate.solve_ivp
    
    Parameters:
    -----------
    t : float
      time 
    params : tuple, floats
      (s,r,b) sigma, r, b parameters
    yy : array, float
      position vector, three components

    Return: 
    -------
    rhs : list, floats 
      RHS new position vector
    '''

    s,r,b = params
    x,y,z = yy
    rhs = array([ s*(y-x), r*x -y -x*z, x*y - b*z])
    return rhs

In [16]:
# set the parameters for this solution
s = 7.0; r = 32; b = 9./3
params = (s,r,b)
tmin,tmax = (0,25)

nmax = 2000
t_eval = linspace(tmin,tmax,nmax)
fun = lambda t,y : lorenz_rhs_ode(t,y,params)
a0  = array([1.,1.,1.])
a0  = array([1.,1.000001,1.])
sol    = integrate.solve_ivp(fun,[tmin,tmax],a0, t_eval = t_eval,rtol=1.e-6 )

#### Time evolution of the components

In [15]:
close(1);figure(1)
plot(sol.t,sol.y[0],label='x')
plot(sol.t,sol.y[1],label='y')
plot(sol.t,sol.y[2],label='z')
xlabel('time'); ylabel("value")
legend()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [17]:
close(11);figure(11)
plot(sol.t,sol.y[0],label='x')
plot(sol.t,sol.y[1],label='y')
plot(sol.t,sol.y[2],label='z')
xlabel('time'); ylabel("value")
legend()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

#### Plot of x vs y component

In [10]:
cm = plt.cm.get_cmap('coolwarm')
n = linspace(1,nmax+1,nmax)
color = cm(n/nmax)[::-1]

In [11]:
close(2);figure(2)
for i in range(nmax-2):
    plot(sol.y[0][i:i+2],sol.y[1][i:i+2],'-',c=color[i],lw=0.75)
plot(sol.y[0][-2],sol.y[1][-2],'o',c=color[-2])
xlabel('x'); ylabel("y")

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0, 0.5, 'y')

In [18]:
close(12);figure(12)
for i in range(nmax-2):
    plot(sol.y[0][i:i+2],sol.y[1][i:i+2],'-',c=color[i],lw=0.75)
plot(sol.y[0][-2],sol.y[1][-2],'o',c=color[-2])
xlabel('x'); ylabel("y")

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0, 0.5, 'y')

In [12]:
close(3);figure(3)
for i in range(nmax-2):
    plot(sol.y[0][i:i+2],sol.y[2][i:i+2],'-',c=color[i],lw=0.75)
plot(sol.y[0][-2],sol.y[2][-2],'o',c=color[-2])
xlabel('x'); ylabel("z")

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0, 0.5, 'z')

In [19]:
close(13);figure(13)
for i in range(nmax-2):
    plot(sol.y[0][i:i+2],sol.y[2][i:i+2],'-',c=color[i],lw=0.75)
plot(sol.y[0][-2],sol.y[2][-2],'o',c=color[-2])
xlabel('x'); ylabel("z")

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0, 0.5, 'z')

#### Last but not least, let's do a 3D plot of the 3D trajectory.

In [13]:
import matplotlib.pyplot as plt
from scipy.integrate import odeint
from mpl_toolkits.mplot3d import Axes3D

In [14]:
ifig=4;close(ifig);fig = plt.figure(ifig)
ax = fig.gca(projection='3d',azim=-30, elev=45)
for i in range(nmax-2):
    ax.plot(sol.y[0][i:i+2],sol.y[1][i:i+2],sol.y[2][i:i+2],'-',c=color[i],lw=0.75)
ax.plot(sol.y[0][-2:-1],sol.y[1][-2:-1],sol.y[2][-2:-1],'o',c=color[-2])
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [20]:
ifig=14;close(ifig);fig = plt.figure(ifig)
ax = fig.gca(projection='3d',azim=-30, elev=45)
for i in range(nmax-2):
    ax.plot(sol.y[0][i:i+2],sol.y[1][i:i+2],sol.y[2][i:i+2],'-',c=color[i],lw=0.75)
ax.plot(sol.y[0][-2:-1],sol.y[1][-2:-1],sol.y[2][-2:-1],'o',c=color[-2])
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

## Recaman sequence

* $a_n = a_{n-1} -n$ if $a_n>0$ and not $\in[a_0, a_1, \dots a_{n-1}]$
* $a_n = a_{n-1} +n$ else
* $a_0 = 0$



### Further exploration:
1. An unsolved question is if all positive integer numbers are part of the sequence. What will be the computational limit be on exploring this question? How can we overcome it? The challenge here will be to store the larges number of integers possible that are part of the sequence already. Just storing all of them in big 64bit integer arrays will get you very far. But imagine you could design a hierarchical number storage structure in which you would store the number of groups of numbers that have been seen? I think one could get pretty far. 
2. In Lab 10.2 Activity 2 you are asked to make a static visualisation plot like the one shown in class. But would it not be nice to have an animation like we did for the oscillating sin curves, where we would see in a movie how the line is evolving, following the path? It may also be nice to have the number ray not evolve on a horizontal direction but on a 45 degree slope. We would all love to see such a movie, and if there are enthusiasts who create such movie we would look at that next Monday together.

