# 5.1 Python programming III: program organization

#### Before we start:
* Quiz 2
* Lab 4.2A2.3 (next time!!!)

#### Today's class:

* Functions an modules
    - Try - except
    - Combine functions into a module for later use
* Python scripts
    - Module as Python script - the test block
    - A module directory
* Units and constants
* Miscellaneous
    - Dictionaries

In [1]:
%pylab

Using matplotlib backend: agg
Populating the interactive namespace from numpy and matplotlib


## Functions and modules
- lambda functions
- `def` 
    * function arguments: mandatory and optional


#### Example lambda function with three arguments

In [2]:
a = 2
f = lambda x,y,z: x**2 * a*sin(y) * mod(z,2)
f(1,1,1)

1.682941969615793

In [3]:
f = lambda x,y,z: 100*x + 10*y + z
f(1,2,3)

123

In [9]:
x=linspace(1,3,3)

In [10]:
y=linspace(4,6,3)
z=linspace(7,9,3)
print(x,y,z)

[1. 2. 3.] [4. 5. 6.] [7. 8. 9.]


In [11]:
f(x,y,z)

array([147., 258., 369.])

Function array arguments will be applied element-wise. What happens when `x=linspace(0,3,4)`?

In [12]:
x=linspace(0,3,4)
print(x,y,z)
f(x,y,z)

[0. 1. 2. 3.] [4. 5. 6.] [7. 8. 9.]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

#### Example temperature def function

In [13]:
def F(C):
    '''Return T in Fahrenheit from input in Celsius'''
    F= 9./5*C+32
    return F

dC=10
C= -30

while C<= 50:
    print("{:5.1f} {:5.1f}".format(C,F(C)))
    C+=dC

-30.0 -22.0
-20.0  -4.0
-10.0  14.0
  0.0  32.0
 10.0  50.0
 20.0  68.0
 30.0  86.0
 40.0 104.0
 50.0 122.0


#### Example def function with detailed doc string and optional argument

In [14]:
def g(x,a=1):
    '''Calculate a*x^2
    
    Parameters
    ----------
    x : float
    input
    
    a : float
    input
    
    Returns
    -------
    g : float
    result
    '''
    g = a*x**2
    return g
g(3)

9

In [15]:
g(3,a=10)

90

You can use access the docstring of your own function in the same way you access it for external functions: 
```Python
g?
```

In [16]:
g?

Signature: g(x, a=1)
Docstring:
Calculate a*x^2

Parameters
----------
x : float
input

a : float
input

Returns
-------
g : float
result
File:      ~/mp248-course-notes/<ipython-input-14-4a71835be4d8>
Type:      function


### Try except
How to _except_ possible errors? For example:

In [17]:
F('4')

TypeError: can't multiply sequence by non-int of type 'float'

The user provides an argument of wrong type to the function. How can we make a function (or any block of code really) more resilient to deal with errors?

In [19]:
def F(C):
    '''Return T in Fahrenheit from input in Celsius'''
    try:
        F= 9./5*C+32
    except TypeError:
        C = float(C)
        F= 9./5*C+32
    return F

In [20]:
F('4')

39.2

### Combine functions into a module for later use

Copy-paste into text file with ending `.py`. This creates python module that can be imported

In [1]:
import mmymod as mymod

In [2]:
mymod.abc

123

In [3]:
#mymod?

In [4]:
mymod.F(25)

77.0

* Adding a module docstring is useful as well! I can also add some constants. 
* Let's try and add a lambda function ... not possible to add optional arguments $\rightarrow$ lambda functions are not meant to be used in modules.

In [5]:
mymod.f(1,1,3)

NameError: name 'a' is not defined

*  Then, let's add `x**2 * sin(y) * mod(z,2)` as a def function. 

In [10]:
mymod.f_multi_arg(1,1,1)

0.8414709848078965

* The module must import all libraries it needs!

## Python scripts
So far we have used code snippets in jupyter notebook cells used interactively. For some applications we need a python program in a script that can be executed on the command line, for example in a batch environment on a big computer such as Niagara of Frontera. 

Let's review shell scripts for a moment, from class notebook `3.2_Linux_terminal_git.ipynb`.

Python scripts can be constructed in the same way by just adding a series of statements into a file with the ending `.py` which can then be executed on the command line as an argument to the python command:

```bash
python pyscript.py
```

Alternatively, one can add the interpreter to the first line just as in the case of the shell script:
```Python
#!/usr/bin/python
a = 5
b = a + 5
print(b)
```
One can then execute just the python script directly as a program.

Specify all parameters at the beginning of the script.
Do not use hard-coded numerical values hidden deep inside your program, and especially declare variable names for any parameters, even if they are used only once. 


Instead of specifying parameters in the script sometimes one may want to use command-line arguments (actually, in practice you probably want to do that less often than you might think). This can be accomplished with the `sys`module:
```Python
import sys
a = float(sys.argv[1])
```
would set `a` when called like this: `./pyscript.py 1`.

In [11]:
import mmymod

### Module as Python script - the test block
Once you have collected a few functions you must make sure that they work they way they are intended. Or you may need the function to exectue a particular task, but you also want to use this collection of functions along with a main program to execute a partucular task. This can be accomplished by adding
```Python
if __name__ == '__main__':    
    <block of statements>
```

### A module directory
As you start adding functions to your own library it may be useful to learn how to organize your own module a bit more conveniently. You may have a collection of module files each ending in `.py` that all belong to the same logical unit of software. An easy way to do this is to create a directory, e.g. `pylib` in your home directory. In that directory create an empty file with the name `__init__.py`. Then add into that directory files with names ending in `.py`. Each of these files is a loadable module in your `pylib` package. You can load the package by adding the path in which the package directory is located (e.g. `/home/user/pylib`) to the python path. 

Let's review environment variables from  class notebook `3.2_Linux_terminal_git.ipynb`.


Just as the system `PATH` variable Python looks in the `PYTHONPATH` for modules.
```Bash
export PYTHONPATH="/home/user/pylib"
```
to your `.bashrc` file (and start a new terminal). Alternatively this can be done from the ipython notebook with the command
```Python
import sys
sys.path.insert(0, '/home/user/pylib') 
```
which will act only on the notebook.

Note: By convention python adopts a single leading underscore for private objects in a module and a double leading underscore for private objects in a class.

In [12]:
import sys
sys.path.insert(0, '/home/user/pylib') 

In [16]:
import mymod_in_lib as lm   # this command will only work if 
                            # there is a file mymod_in_lib.py in
                            # /home/user/pylib and that dir is set
                            # up as described above

ModuleNotFoundError: No module named 'mymod_in_lib'

In [17]:
lm.F(20)

68.0

#### Taking it further
* One can take this one step further, and create libraries that consist of several modules, each of which has a number of python module files with different functions.
* One can add a `setup.py` file which defines dependencies so that a python package becomes installable. It can then be installed directly using the `pip` program from a git repository, such as the [PyPPM](https://github.com/PPMstar/PyPPM) package our group is maintaining. Once that is in place it is only a small further step to make your package installable via [PyPi](https://pypi.org), such as the [NuGrid](https://pypi.org/project/NuGridpy) package for which we are a main developer.  


## Units and constants

Physics is about numbers with units. We can draw units into our python work using - of course - appropriate packages. 
There are several packages now that provide unit support, including
* [Astropy](http://docs.astropy.org/en/v0.2.1/units/index.html), also offers [constants](http://docs.astropy.org/en/stable/constants/)
* [SymPy](http://docs.sympy.org/1.0/modules/physics/units.html)
* [Pint](https://pint.readthedocs.io/en/latest)


Here is an example:
* Calculate how long a $50\mathrm{W}$ light bulb could shine with the energy that is consumed by destruction when a car weighing $1.3\mathrm{t}$ going at $120\mathrm{km/h}$ hits a rigid wall.
* Before solving this problem make a guess! You may be surprised.

### Astropy
#### Units

In [18]:
# import astropy unitis package and define variables
import astropy.units as u

In [19]:
u.kg

Unit("kg")

In [20]:
m = 1300 * u.kg
v = 120 *u.km/u.hr
E = 0.5*m*v**2
P = 50 * u.watt

In [21]:
P

<Quantity 50. W>

Print energy in different units:

In [22]:
print (E)

9360000.0 kg km2 / h2


In [23]:
print (E.si)

722222.2222222221 m N


In [24]:
print (E.to('erg'))

7222222222222.221 erg


In [26]:
u.erg.find_equivalent_units()

  Primary name | Unit definition        | Aliases     
[
  J            | kg m2 / s2             | Joule, joule ,
  Ry           | 2.17987e-18 kg m2 / s2 | rydberg      ,
  eV           | 1.60218e-19 kg m2 / s2 | electronvolt ,
  erg          | 1e-07 kg m2 / s2       |              ,
]

In [27]:
# calculate time
t = E / P
print (t.si)
print (t.to('hr'))

14444.444444444443 s
4.012345679012346 h


#### Constants
`astropy` also provides constants:

In [28]:
from astropy import constants as const
const.L_sun

<<class 'astropy.constants.iau2015.IAU2015'> name='Nominal solar luminosity' value=3.828e+26 uncertainty=0.0 unit='W' reference='IAU 2015 Resolution B 3'>

In [29]:
const.G.value

6.67408e-11

In [30]:
const.u  # atomic mass unit

<<class 'astropy.constants.codata2014.CODATA2014'> name='Atomic mass' value=1.66053904e-27 uncertainty=2e-35 unit='kg' reference='CODATA 2014'>

### Using sympy

In [32]:
# import sympy unitis package and define variables
import sympy.physics.units as u
u.find_unit('power')

['W', 'watt', 'watts', 'planck_power', 'optical_power']

In [33]:
u.find_unit(u.power)

['W', 'watt', 'watts', 'planck_power']

In [34]:
u.W

watt

In [35]:
v = 5000*u.meter/u.second

In [36]:
km=1000*u.meters/ u.kilometer

In [37]:
v/km

5*kilometer/second

In [38]:
ww = u.kilogram * u.meter**2 /u.second**3

In [39]:

m = 1300000 * u.g
v = 120 *u.km/u.hour
E = 0.5*m*v**2
P = 50 * u.watt

In [40]:
# calculate time
t = E / P
print (t*(u.watt/ww) * (1000*u.meter/u.kilometer)**2 / (1000*u.gram/u.kilogram) /(3600*u.seconds/u.hour)**3)

4.01234567901235*hour


## Miscellaneous


### Dictionaries

In [41]:
ages={}
ages["Paul"]=54
ages

{'Paul': 54}

In [42]:
ages = {'Anna':25,'Frank':17,'Gandalf':107}  # a dictionary
print(ages['Frank'])

17


In [43]:
ages.values()

dict_values([25, 17, 107])

In [44]:
%pylab

Using matplotlib backend: module://ipympl.backend_nbagg
Populating the interactive namespace from numpy and matplotlib


In [45]:
array(list(ages.values()))

array([ 25,  17, 107])

In [46]:
list(ages.keys())


['Anna', 'Frank', 'Gandalf']