# 8.2 Linear Algebra

#### Before we start:
* midterm
* finish Lorenz equations from last class

#### Today's class:

##### Linear Algebra
* Basic matrix and vector operations
* Linear transformations
* Solving systems of equationsd
    

## Basic matrix and vector operations

### Vector operations

In [5]:
# numpy arrays may behave like vectors, however ...
import numpy as np

a = [1, 2, 3] 
b = [4, 5, 6]

u = np.array(a)
v = np.array(b)
u*v

array([ 4, 10, 18])

This is an element-wise operation but not any of the vector operations that we are familiar with! 

Instead we need to use explicitely the dot product provided by numpy:

In [6]:
np.dot(u,v)

32

Numpy objects have methods associated with them to perform operations associated with the object, such as the dot product. The [cross product](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cross.html) is a stand-alone numpy function.

In [10]:
# cross product 
a=np.array([1,2,3])
b=np.array([3,2,1])
np.cross(a,b)

array([-4,  8, -4])

### Numpy.matrix
A [matrix](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html) is a specialized 2-D array that retains its 2-D nature through operations. 
 

In [11]:
T = np.matrix([[1, 2], [3, 4]])
v=np.array([1,2])

In [12]:
T

matrix([[1, 2],
        [3, 4]])

In [13]:
v

array([1, 2])

In [14]:
T.dot(v)

matrix([[ 5, 11]])

In [16]:
T.T

matrix([[1, 3],
        [2, 4]])

A couple of examples of array manipulation methods in numpy:
    
* [numpy.concatenate](https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html)
* [numpy.roll](https://docs.scipy.org/doc/numpy/reference/generated/numpy.roll.html)
* [numpy.ravel](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ravel.html)
* [numpy.reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html#numpy.reshape)


In [ ]:
numpy.concatenate ...


### Linear Algebra

Resources:

* Linear Algebra:
    * Chapter 6 in [Newman: Computational Physics _with Python_](http://www-personal.umich.edu/~mejn/computational-physics) (available in the library).
    * many resources on the internet, e.g. [Linear Algebra Primer](https://plot.ly/python/linear-algebra/)
* [Array creation in Python](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html)
* more Python programming with arrays for example in Chapter 5 in [Langtangen: A Primer on Scientific Programming with Python](http://voyager.library.uvic.ca/vwebv/holdingsInfo?searchId=4972&recCount=25&recPointer=13&bibId=2865846) (available as ebook from the UVic library)

## Linear transfromations in 2D
We can use matrices to express linear transformations of   2D sets of points (or any object). Typical transformations are reflection, rotation or scaling, see [Examples of linear transformation matrices](https://en.wikipedia.org/wiki/Linear_map). Let's implement a framework to experiment with such linear maps. 

In [57]:
%pylab ipympl

# populate the 2D points array that contains the cos and sin of 
# the 2pi full circle with n angles
n=50
points=[[cos(2*pi*t/n),sin(2*pi*t/n)] for t in range(n)]

Populating the interactive namespace from numpy and matplotlib


/usr/local/lib/python3.6/dist-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['size']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [58]:
# these are the x coordinates
array(points).T[0]

array([ 1.        ,  0.9921147 ,  0.96858316,  0.92977649,  0.87630668,
        0.80901699,  0.72896863,  0.63742399,  0.53582679,  0.42577929,
        0.30901699,  0.18738131,  0.06279052, -0.06279052, -0.18738131,
       -0.30901699, -0.42577929, -0.53582679, -0.63742399, -0.72896863,
       -0.80901699, -0.87630668, -0.92977649, -0.96858316, -0.9921147 ,
       -1.        , -0.9921147 , -0.96858316, -0.92977649, -0.87630668,
       -0.80901699, -0.72896863, -0.63742399, -0.53582679, -0.42577929,
       -0.30901699, -0.18738131, -0.06279052,  0.06279052,  0.18738131,
        0.30901699,  0.42577929,  0.53582679,  0.63742399,  0.72896863,
        0.80901699,  0.87630668,  0.92977649,  0.96858316,  0.9921147 ])

In [59]:
# save x and y coordinates for easy plotting
x=array(points).T[0]; y=array(points).T[1]

In [60]:
ifig=10;close(ifig);figure(ifig)
plot(x,'x')
plot(y,'o')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [61]:
# plot circle 
ifig=11;close(ifig);fig=figure(ifig)
size=7
fig.canvas.layout.height = str(size)+'in'   # This is a hack to prevent ipympl
fig.canvas.layout.width  = str(size)+'in'   # to adjust horizontal figure size



plot(x,y,'o')
xlim(-2,2);ylim(-2,2)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(-2, 2)

We will now experiment with some of the linear transformation matrices given on the [Linear map](https://en.wikipedia.org/wiki/Linear_map#Examples) Wikipedia page.

In [62]:
# squeeze mapping:
T1 = matrix([[2,0],[0,1./2]])
T1

matrix([[2. , 0. ],
        [0. , 0.5]])

In [63]:
# each point will be individually subjected to the transformation matrix
#
# points is a list, what we need is an array of vectors (x_i,y_i), where each vector has 
# the x and y components of point i. 
#
# therefore: turn into array of tupples

vecs=array(points)

In [64]:
vecs[5]

array([0.80901699, 0.58778525])

In [65]:
# apply transformation matrix to one vector as an example
T1.dot(vecs[3]).A1  # .A1 return flattened ndarray

array([1.85955297, 0.18406228])

In [66]:
# now do this for all vectors (= points)

T = T1
trans_vec = []
for i in range(len(vecs)):
    this_tv = T.dot(vecs[i]).A1
    trans_vec.append(this_tv)

# transpose to make plotable arrays
xt=array(trans_vec).T[0]; yt=array(trans_vec).T[1]

# plot all transformed points to same plot
ifig=11;figure(ifig)
plot(xt,yt,'*',label='squeeze transformation')
legend()

Next we will try a couple more examples:

In [67]:
# horizontal shear mapping
T2 = matrix([[1,1.5],[0,1]])

In [68]:
T = T2

# transformation:
# vecs = trans_vec  # uncomment - result of previous trans is input for next
trans_vec = []
for i in range(len(vecs)):
    this_tv = T.dot(vecs[i]).A1
    trans_vec.append(this_tv)
trans_vec.append(trans_vec[0])
# transpose to make plotable arrays
xt=array(trans_vec).T[0]; yt=array(trans_vec).T[1]

# plot
ifig=11;figure(ifig)
plot(xt,yt,'h--',label="horizontal shear")
legend()

In [49]:
# reflection against y-axis
T3 = matrix([[-1,0],[0,1]])

In [50]:
T = T3

# transformation:
vecs = trans_vec   # uncomment - result of previous trans is input for next
trans_vec = []
for i in range(len(vecs)):
    this_tv = T.dot(vecs[i]).A1
    trans_vec.append(this_tv)

# transpose to make plotable arrays
xt=array(trans_vec).T[0]; yt=array(trans_vec).T[1]

# plot
ifig=11;figure(ifig)
plot(xt,yt,'rd:',label="reflection y-axis")
legend()

## Linear Algebra: Systems of equations

* Many problems require finding solutions to systems of linear equations.
* Example problem: a circuit of resistors.
* Other examples include solving coupled ODEs with multiple variables.
* We will solve linear systems of equations via Gaussian elimination.

### Circuit of resistors
#### The problem
A circuit of resistors, all with the same resistance, connects ground with a power rail at the voltage $V_\mathrm{Rail}$ as shown in this diagram: ![Resistor](Figs/ResistorCircuit.png)

A common problem in physics may involve that we  want to know the voltages at each of the junctions, $V_1, V_2, \dots$ when $V_\mathrm{Rail}$ is given and all resistors have the same  resistance $R$.

The physics of this problem involves two aspects:
1. Kirchhoff current law (a conservation law): The sum of all currents at any junction points must be zero.
2. Ohm's law: The relation between current $I$, voltage $V$ and resistance is $$R = \frac{V}{I}$$

These fundamental electricitiy problems can be best understood in terms of the water analogy. 

### Set up equations
* The current between two junctions is given by the voltage difference divided by the resistance (Ohm's law).
* For each junction the sum of the currents into (or out of) the junction must be zero, i.e. in the voltage differences must contain the voltage at the junction with the same sign 
* Since the resistance is the same for all resistors it cancels and I we can omit it right from the beginning. 
* $V_\mathrm{Rail} = 5 \mathrm{V}$

The sum of the voltage differences at each junction is as follows:

- v3: $(V_3 - V_4) + (V_3 -5) + (V_3 - V_1) = 0$
- v2: $(V_2 - V_4) + (V_2 - 0) + (V_2 - V_1) = 0$
- v1: $(V_1 - V_3) + (V_1 - 0) + (V_1 - V_2) + (V_1 - V_4) = 0$
- v4: $(V_4 - 5) + (V_4 - V_3) + (V_4 - V_2) + (V_4 - V_1) = 0$

You will need to simplify the equations in the four variables $V_1, V_2, V_3$ and $V_4$ and then solve the linear system of equations, which we will do in the lab.

### Another example
Let's look at this example of a coupled system of linear equations and see how to solve:

$$\begin{eqnarray*}
 2 v_1 + 2 v_2 + 3 v_3 &= 1 \\ 
 4 v_1 + 5 v_2 + 5 v_3 &= 4 \\
 v_1 + 2 v_2 + v_3 &= 2
\end{eqnarray*}$$

In this case you have three equations, three variables - this is solvable (unless the equations are not independent).  

### Gaussian elimination

The work horse of solving systems of linear equations is the Gaussian elimination method. Many improvements can be made to the basic idea. Let's see how it works. The above system of equations can be written as  $\vec{u} = \matrix{A} \cdot \vec{v}$ with 

$$
\matrix{A} = \pmatrix{ 2 & 2 & 3 \\ 
                       4 & 5 & 5 \\
                       1 & 2 & 1 }
$$

and $$\vec{u} = \pmatrix{1\\4\\2}.$$ The vector $\vec{v}$ is the desired solution to the coupled system of linear equations given above. [Gaussian elimination](https://en.wikipedia.org/wiki/Gaussian_elimination) is a systematic method to accomplish this.

Recall the important notion from linear algebra that the solution will not change if
* we multiply an equation by any number, or if
* we add and substract equations from each other. 

With this a scheme that finds numerically $vec{v}$ by using these rules looks like this:

1. divide 1$^\mathrm{st}$ equation by $a_{11} (= 2)$:
$$\begin{eqnarray*}
 v_1 + v_2 + \frac{3}{2} v_3 &= \frac{1}{2} \\ 
 4 v_1 + 5 v_2 + 5 v_3 &= 4 \\
 v_1 + 2 v_2 +  v_3 &= 2
\end{eqnarray*}$$
2. substract $a_{21} (= 4)$ times 1$^\mathrm{st}$ equation from 2$^\mathrm{nd}$ equation:
$$\begin{eqnarray*}
 v_1 + 1 v_2 + \frac{3}{2} v_3 &= \frac{1}{2} \\ 
                   1 v_2 - 1 v_3 &= 2 \\
 v_1 + 2 v_2 + 1 v_3 &= 2
\end{eqnarray*}$$
3. substract $a_{31} (= 1)$ times 1$^\mathrm{st}$ equation from 3$^\mathrm{rd}$ equation:
$$\begin{eqnarray*}
 v_1 + v_2 + \frac{3}{2} v_3 &= \frac{1}{2} \\ 
       v_2 -             v_3 &= 2 \\
       v_2 - \frac{1}{2} v_3 &= \frac{3}{2}
\end{eqnarray*}$$
the result is that the first column disappeared in all but the first row
4. repeat for remaining set of equations excluding first row
$$\begin{eqnarray*}
 v_1 + v_2 + \frac{3}{2} v_3 &= \frac{1}{2} \\ 
       v_2 -             v_3 &= 2 \\
             \frac{1}{2} v_3 &= -\frac{1}{2}
\end{eqnarray*}$$
5. repeat until entire set of equations is in triangular form and last equation has only one variable
6. backsubstitution: solve last equation, substitute into last-but-one, solve, substitute etc.

The solution should be $$\vec{v} = \pmatrix{1 \\ 1 \\ -1 }$$ 

Let's see how this can be implemented:

In [ ]:
# reset A
ar1=array([2,2,3])
ar2=array([4,5,5])
ar3=array([1,2,1])
A=array([ar1,ar2,ar3])
u = array([1,4,2])
print(A,u)

I need to apply the same operation to the right-hand side, i.e. $\vec{u}$. The easiest way to do this is to add $\vec{u}$ as an additional column to my working copy `AA` of the matrix `A`. I can use numpy `vstack` for that again, but add to `A.T` instead of `A`, and then take the transpose again:

In [ ]:
AA = vstack((A.T,u)).T      # vstack is a numpy function!
print(AA)

I will start by performing the first step by hand. That will give me some ideas how to compactify and generalize the algorithm into a routine.

1. divide 1$^\mathrm{st}$ equation by $a_{11} (= 2)$:

In [ ]:
# I will be working with rows:
i=0
AA[i] = AA[i]/AA[i,0]

In [ ]:
AA

Here we can see a problem. The $3^\mathrm{rd}$ element in the first row should be $1.5$ and the last should be $0.5$. The matrix `AA` has data type`dtype('int64')`. It needs to be a float. I must check for this situation and change the dtype to float. 

In [ ]:
if not 'float' in str(AA.dtype): # there are different types of floats
    AA=AA.astype(float) 
    # and integer data types, e.g. int32, int64
    # and this way I am checking in the most general way
    # I will also not overwrite A but create a new working array with the 
    # required float data type
print(AA)

In [ ]:
#  now try again
i=0
AA[i] = AA[i]/AA[i,0]

In [ ]:
AA

In [ ]:
# This loop allows me to perform step 2 and 3: 
i=0
for j in range(i,len(A)): print(j)

In [ ]:
i=0
for j in range(i+1,len(AA)):
    print (i,j)
    AA[j] -= AA[j,0]*AA[i]
    print(AA[j])

In [ ]:
AA

Now, I will repeat this with `i=1` [I discover that of course the second index in `AA[j,0]` needs to be updated as well

In [ ]:
i=1
AA[i] = AA[i]/AA[i,i]
for j in range(i+1,len(AA)):
    print (i,j)
    AA[j] -= AA[j,i]*AA[i]
    print(AA[j])

In [ ]:
# check that AA is still what they should be, if not 
# reset by going back to the cell:
AA

Executing again with `i=2` gives the desired diagonal form.

Now we just need to implement the back-substitution

In [ ]:
BB=copy(AA)
m  = len(A)-1     # highest row/col index (we do only square matrices)
v  = zeros(m+1,float) 
u  = BB.T[-1]       # extract RHS
AA = delete(BB,m+1,1) # recover diagonalized coefficient matrix  

In [ ]:
v[m] = u[m]

In [ ]:
v[m-1] = u[m-1] - v[m]*AA[m-1,m]

In [ ]:
v

In [ ]:
v[m-2] = u[m-2] - v[m]*AA[m-2,m] - v[m-1]*AA[m-2,m-1]

This can be made into a loop. However, I realize that this can be generalized in the following way. If we go backwards and initialize `v` as `zeros()` then I may just always subtract from the u component the dot product of `v` and the respective row of `AA`:

In [ ]:
for j in range(m,-1,-1): print(j)

In [ ]:
# reset AA and u:
AA,u

In [ ]:
for j in range(m,-1,-1):
    v[j] = u[j] - v.dot(AA[j])

In [ ]:
v

While it is instuctive to see how we can implement Gaussian elimination in practice we will prefer to use a library.

### Solution with numpy.linalg

As an example we define a matrix $\matrix{A}$ and carry out the dot product with a vector $vec{u}$. 

In [54]:
import numpy as np
A=np.matrix([[1,2],[1,1]])
u=np.array([3,1])
A.dot(u)

matrix([[5, 4]])

$ \matrix{A} \cdot \vec{u} = \vec{v}$, given $\vec{v}$ and $\matrix{A}$ what is $\vec{u}$?

In [55]:
A

matrix([[1, 2],
        [1, 1]])

In [52]:
v=np.array([5,4])
np.linalg.solve(A,v)

array([3., 1.])